apiVersion: v1
kind: ConfigMap
metadata:
  name: vault-proxy-config
  namespace: flask-app
data:
  nginx.conf: |
    events {
      worker_connections 1024;
    }
    http {
      # Basic security headers
      add_header X-Content-Type-Options "nosniff" always;
      
      server {
        listen 8200;
        
        location / {
          proxy_pass http://10.0.0.1:8200;
          proxy_set_header Host $host;
          proxy_set_header X-Real-IP $remote_addr;
          proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
          proxy_set_header X-Forwarded-Proto $scheme;
          
          # Timeouts
          proxy_connect_timeout 60s;
          proxy_send_timeout 60s;
          proxy_read_timeout 60s;
        }
      }
    } 