---
- name: Initial Firewall Setup
  hosts: "{{ vm_name }}_private"
  become: true
  tasks:
    - name: Allow localhost traffic
      iptables:
        table: filter
        chain: INPUT
        in_interface: lo
        jump: ACCEPT
        comment: Allow localhost
        state: present

    - name: Allow established connections
      iptables:
        table: filter
        chain: INPUT
        match: state
        ctstate: ESTABLISHED,RELATED
        jump: ACCEPT
        comment: Allow established connections
        state: present

    - name: Allow SSH from public IP
      iptables:
        table: filter
        chain: INPUT
        protocol: tcp
        destination_port: 22
        source: 0.0.0.0/0
        jump: ACCEPT
        comment: Allow SSH from public IP
        state: present

    - name: Allow WireGuard UDP traffic
      iptables:
        table: filter
        chain: INPUT
        protocol: udp
        destination_port: 51820
        source: 0.0.0.0/0
        jump: ACCEPT
        comment: Allow WireGuard UDP traffic
        state: present

    - name: Allow Vault (port 8200) from WireGuard interface
      iptables:
        table: filter
        chain: INPUT
        in_interface: wg0
        protocol: tcp
        destination_port: 8200
        jump: ACCEPT
        comment: Allow Vault API from WireGuard
        state: present

    - name: Set default policies
      iptables:
        chain: "{{ item.chain }}"
        policy: "{{ item.policy }}"
        state: present
      with_items:
        - { chain: 'INPUT', policy: 'DROP' }
        - { chain: 'FORWARD', policy: 'DROP' }
        - { chain: 'OUTPUT', policy: 'ACCEPT' }

    - name: Save iptables rules
      shell: netfilter-persistent save
      args:
        creates: /etc/iptables/rules.v4

    - name: Display current iptables rules
      shell: iptables -L -v -n
      register: iptables_output

    - name: Show iptables rules
      debug:
        var: iptables_output.stdout_lines 
    
    - name: Save final iptables rules
      shell: netfilter-persistent save

    - name: Display final iptables rules
      shell: iptables -L -v -n
      register: iptables_output

    - name: Show final iptables rules
      debug:
        var: iptables_output.stdout_lines 