---
- name: Final Firewall Hardening
  hosts: "{{ vm_name }}_private"
  become: true
  vars:
    ansible_user: "{{ lookup('file', '../00utils/values.json') | from_json | json_query('nodes.' + vm_name + '.user.public') }}"
    ansible_ssh_private_key_file: /Users/sil/.ssh/{{ vm_name }}_key
  tasks:
    - name: Wait for WireGuard connection
      pause:
        seconds: 30
        prompt: "Please connect to the server via WireGuard (10.0.0.1) to verify the connection works. Press Enter when ready to proceed with final security rules."

    - name: Verify WireGuard connection
      shell: ping -c 1 10.0.0.1
      register: ping_result
      ignore_errors: true

    - name: Remove existing SSH ACCEPT rule for public IP
      iptables:
        table: filter
        chain: INPUT
        protocol: tcp
        destination_port: 22
        source: "!10.0.0.0/24"
        jump: ACCEPT
        comment: Allow SSH from public IP
        state: absent
      when: ping_result.rc == 0

    - name: Remove public IP SSH access only if WireGuard is working
      iptables:
        table: filter
        chain: INPUT
        protocol: tcp
        destination_port: 22
        jump: DROP
        comment: Remove public IP SSH access
        state: present
      when: ping_result.rc == 0

    - name: Save final iptables rules
      shell: netfilter-persistent save

    - name: Display final iptables rules
      shell: iptables -L -v -n
      register: iptables_output

    - name: Show final iptables rules
      debug:
        var: iptables_output.stdout_lines 